<?php
	// load object manager
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

	// get base url
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$baseUrl = $storeManager->getStore()->getBaseUrl();

	if ($block->getCurrentForm()){
		$formFactor = $block->getCurrentForm();
		$isCustomPage = 1;
	} else if ($formCode = $block->getFormCode()){
		$formFactor = $objectManager->create('Incipio\FormFactor\Model\FormFactor\LoadByCode')->loadByCode($formCode);
	}

	if ($block->getSource()){
		$source = $block->getSource();
	} else {
		$source = 'custom';
	}
	
	if ($formFactor->getFormfactorId()){
?>

<div class="form-factor-hero">
	<img class="form-factor-hero-img" src="<?php echo $baseUrl . $formFactor->getHeroImage() ?>" alt="<?php echo $formFactor->getHeroTitle() ?>">
	<div class="form-factor-hero-content">
		<div class="form-factor-hero-info">
			<h1 class="form-factor-hero-title" style="color:<?php echo $formFactor->getHeroColor() ?>"><?php echo $formFactor->getHeroTitle() ?></h1>
			<p class="form-factor-hero-desc" style="color:<?php echo $formFactor->getHeroColor() ?>"><?php echo $formFactor->getHeroDesc() ?></p>
			<?php if (!$formFactor->getCategory() && $source != 'product'){ ?>
				<button class="form-factor-hero-button">Shop Now</button>
			<?php } else { ?>
				<button class="form-factor-hero-button-2" style="color:<?php echo $formFactor->getHeroColor() ?> !important;border:1px solid <?php echo $formFactor->getHeroColor() ?> !important;">Shop Now</button>
			<?php } ?>
		</div>
	</div>
</div>
<?php if ($formFactor->getDeviceSliderStatus() && $source != 'product'){ ?>
<div class="form-factor-devices">
	<div class="form-factor-slider-title">
		Find <?php echo $formFactor->getName(); ?> for your favorite device
	</div>
	<div class="form-factor-slider">
		<?php echo $formFactor->getDeviceSlider(); ?>
	</div>
</div>
<?php } ?>
<div class="form-factor-utility">
	<div class="form-factor-utility-img-block">
		<?php if (strpos($formFactor->getUtilityMedia(), '.mp4') !== false){ ?>
		<video class="form-factor-utility-vid" width="100%" height="100%" autoplay loop muted>
		  <source src="<?php echo $baseUrl . $formFactor->getUtilityMedia() ?>" type="video/mp4">
		</video>
		<?php } else { ?>
		<img src="<?php echo $baseUrl . $formFactor->getUtilityMedia() ?>" alt="<?php echo $formFactor->getUtilityTitle() ?>" class="form-factor-utility-img">
		<?php } ?>
	</div>
	<div class="form-factor-utility-content">
		<h2 class="form-factor-utility-title"><?php echo $formFactor->getUtilityTitle() ?></h2>
		<p class="form-factor-utility-desc"><?php echo $formFactor->getUtilityDesc() ?></p>
	</div>
</div>

<div class="form-factor-features" style="background:<?php echo $formFactor->getFeatureBgcolor() ?>">
	<div class="form-factor-features-block">
		<div class="form-factor-features-content">
			<?php if ($formFactor->getFeatureTitle()){ ?>
			<h3 class="form-factor-features-title"><?php echo $formFactor->getFeatureTitle() ?></h3>
			<?php } ?>
			<?php if ($formFactor->getFeatureDesc()){ ?>
			<p class="form-factor-features-desc"><?php echo $formFactor->getFeatureDesc() ?></p>
			<?php } ?>
			<div class="form-factor-features-feats">
				<div class="form-factor-features-num">1</div>
				<p class="form-factor-features-feat"><?php echo $formFactor->getFeatureOne() ?></p>
			</div>
			<div class="form-factor-features-feats">
				<div class="form-factor-features-num">2</div>
				<p class="form-factor-features-feat"><?php echo $formFactor->getFeatureTwo() ?></p>
			</div>
			<div class="form-factor-features-feats">
				<div class="form-factor-features-num">3</div>
				<p class="form-factor-features-feat"><?php echo $formFactor->getFeatureThree() ?></p>
			</div>
			<div class="form-factor-features-feats">
				<div class="form-factor-features-num">4</div>
				<p class="form-factor-features-feat"><?php echo $formFactor->getFeatureFour() ?></p>
			</div>
			<div class="form-factor-features-feats">
				<div class="form-factor-features-num">5</div>
				<p class="form-factor-features-feat"><?php echo $formFactor->getFeatureFive() ?></p>
			</div>
		</div>
		<div class="form-factor-features-img-block">
			<img class="form-factor-features-img" src="<?php echo $baseUrl . $formFactor->getFeatureImage() ?>" alt="<?php echo $formFactor->getHeroTitle() ?> Features">
		</div>
	</div>
</div>

<?php if ($formFactor->getSecondFeatureOne()){ ?>
	<div class="form-factor-features form-factor-features-2" style="background:<?php echo $formFactor->getSecondFeatureBgcolor() ?>">
		<div class="form-factor-features-block">
			<div class="form-factor-features-content">
				<?php if ($formFactor->getSecondFeatureTitle()){ ?>
				<h3 class="form-factor-features-title"><?php echo $formFactor->getSecondFeatureTitle() ?></h3>
				<?php } ?>
				<?php if ($formFactor->getSecondFeatureDesc()){ ?>
				<p class="form-factor-features-desc"><?php echo $formFactor->getSecondFeatureDesc() ?></p>
				<?php } ?>
				<div class="form-factor-features-feats">
					<div class="form-factor-features-num">1</div>
					<p class="form-factor-features-feat"><?php echo $formFactor->getSecondFeatureOne() ?></p>
				</div>
				<div class="form-factor-features-feats">
					<div class="form-factor-features-num">2</div>
					<p class="form-factor-features-feat"><?php echo $formFactor->getSecondFeatureTwo() ?></p>
				</div>
				<div class="form-factor-features-feats">
					<div class="form-factor-features-num">3</div>
					<p class="form-factor-features-feat"><?php echo $formFactor->getSecondFeatureThree() ?></p>
				</div>
				<div class="form-factor-features-feats">
					<div class="form-factor-features-num">4</div>
					<p class="form-factor-features-feat"><?php echo $formFactor->getSecondFeatureFour() ?></p>
				</div>
				<div class="form-factor-features-feats">
					<div class="form-factor-features-num">5</div>
					<p class="form-factor-features-feat"><?php echo $formFactor->getSecondFeatureFive() ?></p>
				</div>
			</div>
			<div class="form-factor-features-img-block">
				<img class="form-factor-features-img" src="<?php echo $baseUrl . $formFactor->getSecondFeatureImage() ?>" alt="<?php echo $formFactor->getHeroTitle() ?> Features">
			</div>
		</div>
	</div>
<?php } ?>

<div class="form-factor-lifestyle">
	<div class="form-factor-lifestyle-block-1">
		<img src="<?php echo $baseUrl . $formFactor->getLifestyleImageLarge() ?>" alt="" class="form-factor-lifestyle-img">
	</div>
	<div class="form-factor-lifestyle-block-2">
		<div class="form-factor-lifestyle-block-sml">
			<img src="<?php echo $baseUrl . $formFactor->getLifestyleImageSmallOne() ?>" alt="" class="form-factor-lifestyle-img">
		</div>
		<div class="form-factor-lifestyle-block-sml">
			<img src="<?php echo $baseUrl . $formFactor->getLifestyleImageSmallTwo() ?>" alt="" class="form-factor-lifestyle-img">
		</div>
	</div>
</div>

<?php if (!$formFactor->getCategory() && $source != 'product'){ ?>
<div class="form-factor-prod" id="form-factor-products-section">
	<div class="form-factor-prod-blocks">
		<div class="form-factor-prod-block">
			<img src="/<?php echo $formFactor->getProductImage() ?>" alt="Incipio Dualpro Case">
		</div>
		<div class="form-factor-prod-block form-factor-prod-content">
			<div class="form-factor-prod-info">
				<h3 class="form-factor-prod-title"><?php echo $formFactor->getProductTitle() ?></h3>
				<p class="form-factor-prod-desc"><?php echo $formFactor->getProductDesc() ?></p>
				<div class="form-factor-prod-price"><?php echo $formFactor->getProductPrice() ?></div>
				<div class="form-factor-prod-spacer"></div>
				<div class="form-factor-prod-choose">
					<div class="form-factor-prod-choose-block">
						<label for="choose-device" class="form-factor-prod-choose-label">Choose your device</label>
					</div>
					<div class="form-factor-prod-choose-block">
						<?php echo $formFactor->getManufacturerOptions() ?>
						<?php echo $formFactor->getDeviceOptions() ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php } ?>

<?php } ?>
